### ISSUE TITLE
undeclared mvn repo for BeanstalkClient dep

### ISSUE THREAD

**Issue by mkmik** [alaz/camel-beanstalk#1]
Hi,

Probably you forgot to add the repository where to found BeanstalkClient:

No versions are present in the repository for the artifact with a range [1.4.4,1.5)
  com.surftools:BeanstalkClient:jar:null

from the specified remote repositories:
  central (http://repo1.maven.org/maven2)

Path to dependency: 
    1) com.osinka:camel-beanstalk:bundle:1.1.4

**Comment by alaz** [comment]
Instructions on building/installing. Closed by c12c2ad874f0b1bda64f319bae7fc30bb42fb0a6
