### ISSUE TITLE
BeanstalkClient now in maven central

### ISSUE THREAD

**Issue by jpeffer** [alaz/camel-beanstalk#6]
I thought I would let you know that the BeanstalkClient is now in maven central and should no longer require people to clone the project and manually build, if this is added to your pom:

```
<dependency>
  <groupId>com.surftools</groupId>
  <artifactId>BeanstalkClient</artifactId>
  <version>1.4.6</version>
</dependency>
```

This artifact actually points to the fork of RTykulsker's original project and now reflects the code under:
https://github.com/jpeffer/JavaBeanstalkClient

**Comment by alaz** [comment]
Thank you, Jonathan
