### ISSUE TITLE
Consider donating to Apache Camel

### ISSUE THREAD

**Issue by davsclaus** [alaz/camel-beanstalk#8]
Hi

Great component. I wonder if you have considered to donate the code to Apache Camel, so we can provide this excellent component out of the box?

Sorry for _misusing_ an issue ticket for this question.

Feel free to just close the ticket if there is no such plan etc.

We love contributions and are happy to see this component in the Apache family.
http://camel.apache.org/contributing.html

Kind regards

Claus Ibsen

**Comment by alaz** [comment]
Hi Claus,

PR: https://github.com/apache/camel/pull/270

Best,
Alexander Azarov

**Comment by davsclaus** [comment]
Thanks a lot. This component will be part of Camel 2.15. Thanks for the donation.
